//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SteamApplication.ServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.ServiceSoap")]
    public interface ServiceSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        SteamApplication.ServiceReference.HelloWorldResponse HelloWorld(SteamApplication.ServiceReference.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<SteamApplication.ServiceReference.HelloWorldResponse> HelloWorldAsync(SteamApplication.ServiceReference.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/login", ReplyAction="*")]
        SteamApplication.ServiceReference.loginResponse login(SteamApplication.ServiceReference.loginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/login", ReplyAction="*")]
        System.Threading.Tasks.Task<SteamApplication.ServiceReference.loginResponse> loginAsync(SteamApplication.ServiceReference.loginRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/register", ReplyAction="*")]
        SteamApplication.ServiceReference.registerResponse register(SteamApplication.ServiceReference.registerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/register", ReplyAction="*")]
        System.Threading.Tasks.Task<SteamApplication.ServiceReference.registerResponse> registerAsync(SteamApplication.ServiceReference.registerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/test", ReplyAction="*")]
        void test();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/test", ReplyAction="*")]
        System.Threading.Tasks.Task testAsync();
        
        // CODEGEN: Generating message contract since element name name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/createGame", ReplyAction="*")]
        SteamApplication.ServiceReference.createGameResponse createGame(SteamApplication.ServiceReference.createGameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/createGame", ReplyAction="*")]
        System.Threading.Tasks.Task<SteamApplication.ServiceReference.createGameResponse> createGameAsync(SteamApplication.ServiceReference.createGameRequest request);
        
        // CODEGEN: Generating message contract since element name name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/updateGame", ReplyAction="*")]
        SteamApplication.ServiceReference.updateGameResponse updateGame(SteamApplication.ServiceReference.updateGameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/updateGame", ReplyAction="*")]
        System.Threading.Tasks.Task<SteamApplication.ServiceReference.updateGameResponse> updateGameAsync(SteamApplication.ServiceReference.updateGameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/removeGame", ReplyAction="*")]
        bool removeGame(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/removeGame", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> removeGameAsync(int id);
        
        // CODEGEN: Generating message contract since element name getGameResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getGame", ReplyAction="*")]
        SteamApplication.ServiceReference.getGameResponse getGame(SteamApplication.ServiceReference.getGameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getGame", ReplyAction="*")]
        System.Threading.Tasks.Task<SteamApplication.ServiceReference.getGameResponse> getGameAsync(SteamApplication.ServiceReference.getGameRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public SteamApplication.ServiceReference.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(SteamApplication.ServiceReference.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public SteamApplication.ServiceReference.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(SteamApplication.ServiceReference.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class loginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="login", Namespace="http://tempuri.org/", Order=0)]
        public SteamApplication.ServiceReference.loginRequestBody Body;
        
        public loginRequest() {
        }
        
        public loginRequest(SteamApplication.ServiceReference.loginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class loginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public loginRequestBody() {
        }
        
        public loginRequestBody(string username, string password) {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class loginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="loginResponse", Namespace="http://tempuri.org/", Order=0)]
        public SteamApplication.ServiceReference.loginResponseBody Body;
        
        public loginResponse() {
        }
        
        public loginResponse(SteamApplication.ServiceReference.loginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class loginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string loginResult;
        
        public loginResponseBody() {
        }
        
        public loginResponseBody(string loginResult) {
            this.loginResult = loginResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class registerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="register", Namespace="http://tempuri.org/", Order=0)]
        public SteamApplication.ServiceReference.registerRequestBody Body;
        
        public registerRequest() {
        }
        
        public registerRequest(SteamApplication.ServiceReference.registerRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class registerRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string role;
        
        public registerRequestBody() {
        }
        
        public registerRequestBody(string username, string password, string role) {
            this.username = username;
            this.password = password;
            this.role = role;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class registerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="registerResponse", Namespace="http://tempuri.org/", Order=0)]
        public SteamApplication.ServiceReference.registerResponseBody Body;
        
        public registerResponse() {
        }
        
        public registerResponse(SteamApplication.ServiceReference.registerResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class registerResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string registerResult;
        
        public registerResponseBody() {
        }
        
        public registerResponseBody(string registerResult) {
            this.registerResult = registerResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class createGameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="createGame", Namespace="http://tempuri.org/", Order=0)]
        public SteamApplication.ServiceReference.createGameRequestBody Body;
        
        public createGameRequest() {
        }
        
        public createGameRequest(SteamApplication.ServiceReference.createGameRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class createGameRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string price;
        
        public createGameRequestBody() {
        }
        
        public createGameRequestBody(string name, string price) {
            this.name = name;
            this.price = price;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class createGameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="createGameResponse", Namespace="http://tempuri.org/", Order=0)]
        public SteamApplication.ServiceReference.createGameResponseBody Body;
        
        public createGameResponse() {
        }
        
        public createGameResponse(SteamApplication.ServiceReference.createGameResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class createGameResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string createGameResult;
        
        public createGameResponseBody() {
        }
        
        public createGameResponseBody(string createGameResult) {
            this.createGameResult = createGameResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class updateGameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="updateGame", Namespace="http://tempuri.org/", Order=0)]
        public SteamApplication.ServiceReference.updateGameRequestBody Body;
        
        public updateGameRequest() {
        }
        
        public updateGameRequest(SteamApplication.ServiceReference.updateGameRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class updateGameRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string price;
        
        public updateGameRequestBody() {
        }
        
        public updateGameRequestBody(int id, string name, string price) {
            this.id = id;
            this.name = name;
            this.price = price;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class updateGameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="updateGameResponse", Namespace="http://tempuri.org/", Order=0)]
        public SteamApplication.ServiceReference.updateGameResponseBody Body;
        
        public updateGameResponse() {
        }
        
        public updateGameResponse(SteamApplication.ServiceReference.updateGameResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class updateGameResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string updateGameResult;
        
        public updateGameResponseBody() {
        }
        
        public updateGameResponseBody(string updateGameResult) {
            this.updateGameResult = updateGameResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getGameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getGame", Namespace="http://tempuri.org/", Order=0)]
        public SteamApplication.ServiceReference.getGameRequestBody Body;
        
        public getGameRequest() {
        }
        
        public getGameRequest(SteamApplication.ServiceReference.getGameRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class getGameRequestBody {
        
        public getGameRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getGameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getGameResponse", Namespace="http://tempuri.org/", Order=0)]
        public SteamApplication.ServiceReference.getGameResponseBody Body;
        
        public getGameResponse() {
        }
        
        public getGameResponse(SteamApplication.ServiceReference.getGameResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getGameResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getGameResult;
        
        public getGameResponseBody() {
        }
        
        public getGameResponseBody(string getGameResult) {
            this.getGameResult = getGameResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSoapChannel : SteamApplication.ServiceReference.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<SteamApplication.ServiceReference.ServiceSoap>, SteamApplication.ServiceReference.ServiceSoap {
        
        public ServiceSoapClient() {
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SteamApplication.ServiceReference.HelloWorldResponse SteamApplication.ServiceReference.ServiceSoap.HelloWorld(SteamApplication.ServiceReference.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            SteamApplication.ServiceReference.HelloWorldRequest inValue = new SteamApplication.ServiceReference.HelloWorldRequest();
            inValue.Body = new SteamApplication.ServiceReference.HelloWorldRequestBody();
            SteamApplication.ServiceReference.HelloWorldResponse retVal = ((SteamApplication.ServiceReference.ServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SteamApplication.ServiceReference.HelloWorldResponse> SteamApplication.ServiceReference.ServiceSoap.HelloWorldAsync(SteamApplication.ServiceReference.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<SteamApplication.ServiceReference.HelloWorldResponse> HelloWorldAsync() {
            SteamApplication.ServiceReference.HelloWorldRequest inValue = new SteamApplication.ServiceReference.HelloWorldRequest();
            inValue.Body = new SteamApplication.ServiceReference.HelloWorldRequestBody();
            return ((SteamApplication.ServiceReference.ServiceSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SteamApplication.ServiceReference.loginResponse SteamApplication.ServiceReference.ServiceSoap.login(SteamApplication.ServiceReference.loginRequest request) {
            return base.Channel.login(request);
        }
        
        public string login(string username, string password) {
            SteamApplication.ServiceReference.loginRequest inValue = new SteamApplication.ServiceReference.loginRequest();
            inValue.Body = new SteamApplication.ServiceReference.loginRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            SteamApplication.ServiceReference.loginResponse retVal = ((SteamApplication.ServiceReference.ServiceSoap)(this)).login(inValue);
            return retVal.Body.loginResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SteamApplication.ServiceReference.loginResponse> SteamApplication.ServiceReference.ServiceSoap.loginAsync(SteamApplication.ServiceReference.loginRequest request) {
            return base.Channel.loginAsync(request);
        }
        
        public System.Threading.Tasks.Task<SteamApplication.ServiceReference.loginResponse> loginAsync(string username, string password) {
            SteamApplication.ServiceReference.loginRequest inValue = new SteamApplication.ServiceReference.loginRequest();
            inValue.Body = new SteamApplication.ServiceReference.loginRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            return ((SteamApplication.ServiceReference.ServiceSoap)(this)).loginAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SteamApplication.ServiceReference.registerResponse SteamApplication.ServiceReference.ServiceSoap.register(SteamApplication.ServiceReference.registerRequest request) {
            return base.Channel.register(request);
        }
        
        public string register(string username, string password, string role) {
            SteamApplication.ServiceReference.registerRequest inValue = new SteamApplication.ServiceReference.registerRequest();
            inValue.Body = new SteamApplication.ServiceReference.registerRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.role = role;
            SteamApplication.ServiceReference.registerResponse retVal = ((SteamApplication.ServiceReference.ServiceSoap)(this)).register(inValue);
            return retVal.Body.registerResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SteamApplication.ServiceReference.registerResponse> SteamApplication.ServiceReference.ServiceSoap.registerAsync(SteamApplication.ServiceReference.registerRequest request) {
            return base.Channel.registerAsync(request);
        }
        
        public System.Threading.Tasks.Task<SteamApplication.ServiceReference.registerResponse> registerAsync(string username, string password, string role) {
            SteamApplication.ServiceReference.registerRequest inValue = new SteamApplication.ServiceReference.registerRequest();
            inValue.Body = new SteamApplication.ServiceReference.registerRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.role = role;
            return ((SteamApplication.ServiceReference.ServiceSoap)(this)).registerAsync(inValue);
        }
        
        public void test() {
            base.Channel.test();
        }
        
        public System.Threading.Tasks.Task testAsync() {
            return base.Channel.testAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SteamApplication.ServiceReference.createGameResponse SteamApplication.ServiceReference.ServiceSoap.createGame(SteamApplication.ServiceReference.createGameRequest request) {
            return base.Channel.createGame(request);
        }
        
        public string createGame(string name, string price) {
            SteamApplication.ServiceReference.createGameRequest inValue = new SteamApplication.ServiceReference.createGameRequest();
            inValue.Body = new SteamApplication.ServiceReference.createGameRequestBody();
            inValue.Body.name = name;
            inValue.Body.price = price;
            SteamApplication.ServiceReference.createGameResponse retVal = ((SteamApplication.ServiceReference.ServiceSoap)(this)).createGame(inValue);
            return retVal.Body.createGameResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SteamApplication.ServiceReference.createGameResponse> SteamApplication.ServiceReference.ServiceSoap.createGameAsync(SteamApplication.ServiceReference.createGameRequest request) {
            return base.Channel.createGameAsync(request);
        }
        
        public System.Threading.Tasks.Task<SteamApplication.ServiceReference.createGameResponse> createGameAsync(string name, string price) {
            SteamApplication.ServiceReference.createGameRequest inValue = new SteamApplication.ServiceReference.createGameRequest();
            inValue.Body = new SteamApplication.ServiceReference.createGameRequestBody();
            inValue.Body.name = name;
            inValue.Body.price = price;
            return ((SteamApplication.ServiceReference.ServiceSoap)(this)).createGameAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SteamApplication.ServiceReference.updateGameResponse SteamApplication.ServiceReference.ServiceSoap.updateGame(SteamApplication.ServiceReference.updateGameRequest request) {
            return base.Channel.updateGame(request);
        }
        
        public string updateGame(int id, string name, string price) {
            SteamApplication.ServiceReference.updateGameRequest inValue = new SteamApplication.ServiceReference.updateGameRequest();
            inValue.Body = new SteamApplication.ServiceReference.updateGameRequestBody();
            inValue.Body.id = id;
            inValue.Body.name = name;
            inValue.Body.price = price;
            SteamApplication.ServiceReference.updateGameResponse retVal = ((SteamApplication.ServiceReference.ServiceSoap)(this)).updateGame(inValue);
            return retVal.Body.updateGameResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SteamApplication.ServiceReference.updateGameResponse> SteamApplication.ServiceReference.ServiceSoap.updateGameAsync(SteamApplication.ServiceReference.updateGameRequest request) {
            return base.Channel.updateGameAsync(request);
        }
        
        public System.Threading.Tasks.Task<SteamApplication.ServiceReference.updateGameResponse> updateGameAsync(int id, string name, string price) {
            SteamApplication.ServiceReference.updateGameRequest inValue = new SteamApplication.ServiceReference.updateGameRequest();
            inValue.Body = new SteamApplication.ServiceReference.updateGameRequestBody();
            inValue.Body.id = id;
            inValue.Body.name = name;
            inValue.Body.price = price;
            return ((SteamApplication.ServiceReference.ServiceSoap)(this)).updateGameAsync(inValue);
        }
        
        public bool removeGame(int id) {
            return base.Channel.removeGame(id);
        }
        
        public System.Threading.Tasks.Task<bool> removeGameAsync(int id) {
            return base.Channel.removeGameAsync(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SteamApplication.ServiceReference.getGameResponse SteamApplication.ServiceReference.ServiceSoap.getGame(SteamApplication.ServiceReference.getGameRequest request) {
            return base.Channel.getGame(request);
        }
        
        public string getGame() {
            SteamApplication.ServiceReference.getGameRequest inValue = new SteamApplication.ServiceReference.getGameRequest();
            inValue.Body = new SteamApplication.ServiceReference.getGameRequestBody();
            SteamApplication.ServiceReference.getGameResponse retVal = ((SteamApplication.ServiceReference.ServiceSoap)(this)).getGame(inValue);
            return retVal.Body.getGameResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SteamApplication.ServiceReference.getGameResponse> SteamApplication.ServiceReference.ServiceSoap.getGameAsync(SteamApplication.ServiceReference.getGameRequest request) {
            return base.Channel.getGameAsync(request);
        }
        
        public System.Threading.Tasks.Task<SteamApplication.ServiceReference.getGameResponse> getGameAsync() {
            SteamApplication.ServiceReference.getGameRequest inValue = new SteamApplication.ServiceReference.getGameRequest();
            inValue.Body = new SteamApplication.ServiceReference.getGameRequestBody();
            return ((SteamApplication.ServiceReference.ServiceSoap)(this)).getGameAsync(inValue);
        }
    }
}
